# Generated by Django 5.2.15 on 2026-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
